package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/flectolab/flecto-manager/auth"
	"github.com/flectolab/flecto-manager/common/types"
	"github.com/flectolab/flecto-manager/graph"
	"github.com/flectolab/flecto-manager/model"
)

// AuthType is the resolver for the authType field.
func (r *activityEventResolver) AuthType(ctx context.Context, obj *model.ActivityEvent) (string, error) {
	// Exposed as a string rather than an enum: the column is empty for events
	// recorded outside of an authenticated request, which no enum value can carry.
	return string(obj.AuthType), nil
}

// ProjectActivityEvents is the resolver for the projectActivityEvents field.
func (r *queryResolver) ProjectActivityEvents(ctx context.Context, namespaceCode string, projectCode string, pagination *types.PaginationInput, filter *graph.ActivityEventFilter) (*types.PaginatedResult[model.ActivityEvent], error) {
	userCtx := auth.GetUser(ctx)
	// The journal spans redirects, pages and the project itself, so read access to
	// any resource of the project is what grants access to it.
	if !r.PermissionChecker.CanResource(userCtx.SubjectPermissions, namespaceCode, projectCode, model.ResourceTypeAny, model.ActionRead) {
		return nil, fmt.Errorf("user %s has no permission to access project %s/%s", userCtx.Username, namespaceCode, projectCode)
	}

	query := r.ActivityService.GetQuery(ctx).
		Where(fmt.Sprintf("%s = ? AND %s = ?", model.ColumnNamespaceCode, model.ColumnProjectCode), namespaceCode, projectCode)

	if filter != nil {
		if filter.Resource != nil {
			query = query.Where("resource = ?", *filter.Resource)
		}
		if filter.Action != nil {
			query = query.Where("action = ?", *filter.Action)
		}
		if filter.Actor != nil && *filter.Actor != "" {
			query = query.Where("actor = ?", *filter.Actor)
		}
		if filter.From != nil {
			query = query.Where("occurred_at >= ?", *filter.From)
		}
		if filter.To != nil {
			query = query.Where("occurred_at <= ?", *filter.To)
		}
	}

	// Newest first, ordered by id: events written by the same operation share their
	// timestamp, only the id is a total order.
	return r.ActivityService.SearchPaginate(ctx, pagination, query.Order("id DESC"))
}

// ActivityEvent returns graph.ActivityEventResolver implementation.
func (r *Resolver) ActivityEvent() graph.ActivityEventResolver { return &activityEventResolver{r} }

type activityEventResolver struct{ *Resolver }
