package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"time"

	"github.com/flectolab/flecto-manager/auth"
	"github.com/flectolab/flecto-manager/common/types"
	"github.com/flectolab/flecto-manager/database"
	"github.com/flectolab/flecto-manager/graph"
	"github.com/flectolab/flecto-manager/model"
)

// LoadDuration is the resolver for the load_duration field.
func (r *agentResolver) LoadDuration(ctx context.Context, obj *model.Agent) (int64, error) {
	return obj.Agent.LoadDuration.Nanoseconds(), nil
}

// SearchAgents is the resolver for the searchAgents field.
func (r *queryResolver) SearchAgents(ctx context.Context, namespaceCode string, projectCode string, pagination *types.PaginationInput, filter graph.AgentFilter, sort []database.SortInput) (*types.PaginatedResult[model.Agent], error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanResource(userCtx.SubjectPermissions, namespaceCode, projectCode, model.ResourceTypeAgent, model.ActionRead) {
		return nil, fmt.Errorf("user %s has no permission to access project %s/%s", userCtx.Username, namespaceCode, projectCode)
	}

	query := r.AgentService.GetQuery(ctx).
		Where(fmt.Sprintf("%s = ? AND %s = ?", model.ColumnNamespaceCode, model.ColumnProjectCode), namespaceCode, projectCode)

	if filter.Search != nil && *filter.Search != "" {
		search := "%" + *filter.Search + "%"
		query = query.Where("name LIKE ?", search)
	}
	if len(filter.Types) > 0 {
		query = query.Where("type IN ?", filter.Types)
	}
	if len(filter.Status) > 0 {
		query = query.Where("status IN ?", filter.Status)
	}

	// By default, hide offline agents (those not updated after the threshold)
	if filter.ShowOffline == nil || !*filter.ShowOffline {
		offlineThreshold := time.Now().Add(-r.AgentConfig.OfflineThreshold)
		query = query.Where("last_hit_at >= ?", offlineThreshold)
	}

	if len(sort) > 0 {
		query = database.ApplySort(query, model.AgentSortableColumns, sort, "")
	}

	return r.AgentService.SearchPaginate(ctx, pagination, query)
}

// Agent returns graph.AgentResolver implementation.
func (r *Resolver) Agent() graph.AgentResolver { return &agentResolver{r} }

type agentResolver struct{ *Resolver }
