package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/flectolab/flecto-manager/auth"
	"github.com/flectolab/flecto-manager/common/types"
	"github.com/flectolab/flecto-manager/graph"
	"github.com/flectolab/flecto-manager/model"
)

// CreatePageDraft is the resolver for the createPageDraft field.
func (r *mutationResolver) CreatePageDraft(ctx context.Context, namespaceCode string, projectCode string, input graph.CreatePageDraft) (*model.PageDraft, error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanResource(userCtx.SubjectPermissions, namespaceCode, projectCode, model.ResourceTypePage, model.ActionWrite) {
		return nil, fmt.Errorf("user %s has no permission to access project %s/%s", userCtx.Username, namespaceCode, projectCode)
	}

	return r.PageDraftService.Create(ctx, namespaceCode, projectCode, input.OldPageID, input.NewPage)
}

// UpdatePageDraft is the resolver for the updatePageDraft field.
func (r *mutationResolver) UpdatePageDraft(ctx context.Context, namespaceCode string, projectCode string, pageDraftID int64, input graph.UpdatePageDraft) (*model.PageDraft, error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanResource(userCtx.SubjectPermissions, namespaceCode, projectCode, model.ResourceTypePage, model.ActionWrite) {
		return nil, fmt.Errorf("user %s has no permission to access project %s/%s", userCtx.Username, namespaceCode, projectCode)
	}
	return r.PageDraftService.Update(ctx, pageDraftID, input.NewPage)
}

// DeletePageDraft is the resolver for the deletePageDraft field.
func (r *mutationResolver) DeletePageDraft(ctx context.Context, namespaceCode string, projectCode string, pageDraftID int64) (bool, error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanResource(userCtx.SubjectPermissions, namespaceCode, projectCode, model.ResourceTypePage, model.ActionWrite) {
		return false, fmt.Errorf("user %s has no permission to access project %s/%s", userCtx.Username, namespaceCode, projectCode)
	}

	return r.PageDraftService.Delete(ctx, pageDraftID)
}

// RollbackPageDraft is the resolver for the rollbackPageDraft field.
func (r *mutationResolver) RollbackPageDraft(ctx context.Context, namespaceCode string, projectCode string) (bool, error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanResource(userCtx.SubjectPermissions, namespaceCode, projectCode, model.ResourceTypePage, model.ActionWrite) {
		return false, fmt.Errorf("user %s has no permission to access project %s/%s", userCtx.Username, namespaceCode, projectCode)
	}

	return r.PageDraftService.Rollback(ctx, namespaceCode, projectCode)
}

// ProjectsPageDrafts is the resolver for the projectsPageDrafts field.
func (r *queryResolver) ProjectsPageDrafts(ctx context.Context, namespaceCode string, projectCode string, pagination *types.PaginationInput, filter *graph.PageDraftFilter) (*types.PaginatedResult[model.PageDraft], error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanResource(userCtx.SubjectPermissions, namespaceCode, projectCode, model.ResourceTypePage, model.ActionRead) {
		return nil, fmt.Errorf("user %s has no permission to access project %s/%s", userCtx.Username, namespaceCode, projectCode)
	}
	query := r.PageDraftService.GetQuery(ctx).Preload("OldPage").
		Where(fmt.Sprintf("%s = ? AND %s = ?", model.ColumnNamespaceCode, model.ColumnProjectCode), namespaceCode, projectCode)

	return r.PageDraftService.SearchPaginate(ctx, pagination, query)
}

// ProjectPageDraft is the resolver for the projectPageDraft field.
func (r *queryResolver) ProjectPageDraft(ctx context.Context, namespaceCode string, projectCode string, pageDraftID int64) (*model.PageDraft, error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanResource(userCtx.SubjectPermissions, namespaceCode, projectCode, model.ResourceTypePage, model.ActionRead) {
		return nil, fmt.Errorf("user %s has no permission to access project %s/%s", userCtx.Username, namespaceCode, projectCode)
	}

	return r.PageDraftService.GetByID(ctx, pageDraftID)
}
