package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/flectolab/flecto-manager/auth"
	"github.com/flectolab/flecto-manager/common/types"
	"github.com/flectolab/flecto-manager/database"
	"github.com/flectolab/flecto-manager/graph"
	"github.com/flectolab/flecto-manager/model"
)

// ProjectsPages is the resolver for the projectsPages field.
func (r *queryResolver) ProjectsPages(ctx context.Context, namespaceCode string, projectCode string, pagination *types.PaginationInput, filter *graph.PageFilter, sort []database.SortInput) (*types.PaginatedResult[model.Page], error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanResource(userCtx.SubjectPermissions, namespaceCode, projectCode, model.ResourceTypePage, model.ActionRead) {
		return nil, fmt.Errorf("user %s has no permission to access project %s/%s", userCtx.Username, namespaceCode, projectCode)
	}

	query := r.PageService.GetQuery(ctx).
		Joins("LEFT JOIN page_drafts ON page_drafts.old_page_id = pages.id").
		Where(fmt.Sprintf("pages.%s = ? AND pages.%s = ?", model.ColumnNamespaceCode, model.ColumnProjectCode), namespaceCode, projectCode)

	if filter != nil {
		if filter.Search != nil && *filter.Search != "" {
			search := "%" + *filter.Search + "%"
			query = query.Where(
				"pages.path LIKE ? OR pages.content LIKE ? OR page_drafts.new_path LIKE ? OR page_drafts.new_content LIKE ?",
				search, search, search, search,
			)
		}
		if len(filter.Types) > 0 {
			query = query.Where("pages.type IN ?", filter.Types)
		}
		if len(filter.ContentTypes) > 0 {
			query = query.Where("pages.content_type IN ?", filter.ContentTypes)
		}
		if len(filter.DraftStatus) > 0 {
			var hasDraftTypes []model.DraftChangeType
			includePublished := false

			for _, status := range filter.DraftStatus {
				if status == model.DraftChangeTypePublished {
					includePublished = true
				} else {
					hasDraftTypes = append(hasDraftTypes, status)
				}
			}

			if len(hasDraftTypes) > 0 && includePublished {
				query = query.Where("page_drafts.change_type IN ? OR page_drafts.change_type IS NULL", hasDraftTypes)
			} else if len(hasDraftTypes) > 0 {
				query = query.Where("page_drafts.change_type IN ?", hasDraftTypes)
			} else if includePublished {
				query = query.Where("page_drafts.change_type IS NULL")
			}
		}
	}

	// Apply sorting
	if len(sort) > 0 {
		query = database.ApplySort(query, model.PageSortableColumns, sort, "pages")
	}

	return r.PageService.SearchPaginate(ctx, pagination, query)
}

// ProjectPage is the resolver for the projectPage field.
func (r *queryResolver) ProjectPage(ctx context.Context, namespaceCode string, projectCode string, pageID int64) (*model.Page, error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanResource(userCtx.SubjectPermissions, namespaceCode, projectCode, model.ResourceTypePage, model.ActionRead) {
		return nil, fmt.Errorf("user %s has no permission to access project %s/%s", userCtx.Username, namespaceCode, projectCode)
	}

	return r.PageService.GetByID(ctx, namespaceCode, projectCode, pageID)
}
