package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/flectolab/flecto-manager/graph"
)

// ProjectDashboard is the resolver for the projectDashboard field.
func (r *queryResolver) ProjectDashboard(ctx context.Context, namespaceCode string, projectCode string) (*graph.ProjectDashboard, error) {
	stats, err := r.ProjectDashboardService.GetStats(ctx, namespaceCode, projectCode)
	if err != nil {
		return nil, err
	}

	return &graph.ProjectDashboard{
		Version:     stats.Version,
		PublishedAt: stats.PublishedAt,
		RedirectStats: &graph.RedirectStats{
			Total:          stats.RedirectTotal,
			CountBasic:     stats.RedirectCountBasic,
			CountBasicHost: stats.RedirectCountBasicHost,
			CountRegex:     stats.RedirectCountRegex,
			CountRegexHost: stats.RedirectCountRegexHost,
		},
		RedirectDraftStats: &graph.RedirectDraftStats{
			Total:       stats.RedirectDraftTotal,
			CountCreate: stats.RedirectDraftCountCreate,
			CountUpdate: stats.RedirectDraftCountUpdate,
			CountDelete: stats.RedirectDraftCountDelete,
		},
		PageStats: &graph.PageStats{
			Total:          stats.PageTotal,
			CountBasic:     stats.PageCountBasic,
			CountBasicHost: stats.PageCountBasicHost,
		},
		PageDraftStats: &graph.PageDraftStats{
			Total:       stats.PageDraftTotal,
			CountCreate: stats.PageDraftCountCreate,
			CountUpdate: stats.PageDraftCountUpdate,
			CountDelete: stats.PageDraftCountDelete,
		},
		AgentStats: &graph.AgentStats{
			TotalOnline: stats.AgentTotalOnline,
			CountError:  stats.AgentCountError,
		},
	}, nil
}
