package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/flectolab/flecto-manager/auth"
	"github.com/flectolab/flecto-manager/common/types"
	"github.com/flectolab/flecto-manager/database"
	"github.com/flectolab/flecto-manager/graph"
	"github.com/flectolab/flecto-manager/model"
)

// Type is the resolver for the type field.
func (r *adminPermissionResolver) Type(ctx context.Context, obj *model.AdminPermission) (string, error) {
	return string(obj.Role.Type), nil
}

// Section is the resolver for the section field.
func (r *adminPermissionResolver) Section(ctx context.Context, obj *model.AdminPermission) (string, error) {
	return string(obj.Section), nil
}

// Action is the resolver for the action field.
func (r *adminPermissionResolver) Action(ctx context.Context, obj *model.AdminPermission) (string, error) {
	return string(obj.Action), nil
}

// CreateRole is the resolver for the createRole field.
func (r *mutationResolver) CreateRole(ctx context.Context, input graph.CreateRoleInput) (*graph.Role, error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanAdmin(userCtx.SubjectPermissions, model.AdminSectionRoles, model.ActionWrite) {
		return nil, fmt.Errorf("user %s has no permission to access %s", userCtx.Username, model.AdminSectionRoles)
	}

	// Validate role name: only alphanumeric, underscore and hyphen allowed
	if !validRoleNameRegex.MatchString(input.Name) {
		return nil, fmt.Errorf("invalid role name: only alphanumeric characters, underscores and hyphens are allowed")
	}

	// Check if role already exists
	existingRole, _ := r.RoleService.GetByCode(ctx, input.Name, model.RoleTypeRole)
	if existingRole != nil {
		return nil, fmt.Errorf("role %s already exists", input.Name)
	}

	// Create the role
	role, err := r.RoleService.Create(ctx, &model.Role{Code: input.Name, Type: model.RoleTypeRole})
	if err != nil {
		return nil, err
	}

	// Set permissions if provided
	subjectPermissions := &model.SubjectPermissions{}
	for _, permission := range input.ResourcePermissions {
		subjectPermissions.Resources = append(subjectPermissions.Resources, model.ResourcePermission{Namespace: permission.Namespace, Project: permission.Project, Action: model.ActionType(permission.Action)})
	}
	for _, permission := range input.AdminPermissions {
		subjectPermissions.Admin = append(subjectPermissions.Admin, model.AdminPermission{Section: model.SectionType(permission.Section), Action: model.ActionType(permission.Action)})
	}

	if len(subjectPermissions.Resources) > 0 || len(subjectPermissions.Admin) > 0 {
		err = r.RoleService.UpdateRolePermissions(ctx, role.ID, subjectPermissions)
		if err != nil {
			return nil, err
		}
	}

	return &graph.Role{Name: role.Code, CreatedAt: role.CreatedAt, UpdatedAt: role.UpdatedAt, Admin: subjectPermissions.Admin, Resources: subjectPermissions.Resources}, nil
}

// UpdateRole is the resolver for the updateRole field.
func (r *mutationResolver) UpdateRole(ctx context.Context, name string, input graph.UpdateRoleInput) (*graph.Role, error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanAdmin(userCtx.SubjectPermissions, model.AdminSectionRoles, model.ActionWrite) {
		return nil, fmt.Errorf("user %s has no permission to access %s", userCtx.Username, model.AdminSectionRoles)
	}

	// Get existing role
	role, err := r.RoleService.GetByCode(ctx, name, model.RoleTypeRole)
	if err != nil {
		return nil, fmt.Errorf("role %s not found", name)
	}

	// Update permissions
	subjectPermissions := &model.SubjectPermissions{}
	for _, permission := range input.ResourcePermissions {
		subjectPermissions.Resources = append(subjectPermissions.Resources, model.ResourcePermission{Namespace: permission.Namespace, Project: permission.Project, Action: model.ActionType(permission.Action)})
	}
	for _, permission := range input.AdminPermissions {
		subjectPermissions.Admin = append(subjectPermissions.Admin, model.AdminPermission{Section: model.SectionType(permission.Section), Action: model.ActionType(permission.Action)})
	}

	err = r.RoleService.UpdateRolePermissions(ctx, role.ID, subjectPermissions)
	if err != nil {
		return nil, err
	}

	// Fetch updated role to get new timestamps
	role, _ = r.RoleService.GetByCode(ctx, name, model.RoleTypeRole)

	return &graph.Role{Name: role.Code, CreatedAt: role.CreatedAt, UpdatedAt: role.UpdatedAt, Admin: subjectPermissions.Admin, Resources: subjectPermissions.Resources}, nil
}

// DeleteRole is the resolver for the deleteRole field.
func (r *mutationResolver) DeleteRole(ctx context.Context, name string) (bool, error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanAdmin(userCtx.SubjectPermissions, model.AdminSectionRoles, model.ActionDelete) {
		return false, fmt.Errorf("user %s has no permission to delete %s", userCtx.Username, model.AdminSectionRoles)
	}

	role, err := r.RoleService.GetByCode(ctx, name, model.RoleTypeRole)
	if err != nil {
		return false, err
	}

	return r.RoleService.Delete(ctx, role.ID)
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]graph.Role, error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanAdmin(userCtx.SubjectPermissions, model.AdminSectionRoles, model.ActionRead) {
		return nil, fmt.Errorf("user %s has no permission to access %s", userCtx.Username, model.AdminSectionRoles)
	}
	roles := make([]graph.Role, 0)
	dbRoles := make([]*model.Role, 0)
	err := r.DB.Model(&model.Role{}).Where("type = ?", model.RoleTypeRole).Find(&dbRoles).Error
	if err != nil {
		return nil, err
	}
	for _, dbRole := range dbRoles {
		role := graph.Role{Name: dbRole.Code, CreatedAt: dbRole.CreatedAt, UpdatedAt: dbRole.UpdatedAt}

		subjectPermissions, errGetPerms := r.RoleService.GetPermissionsByRoleCode(ctx, dbRole.Code)
		if errGetPerms != nil {
			return nil, errGetPerms
		}
		role.Resources = subjectPermissions.Resources
		role.Admin = subjectPermissions.Admin

		roles = append(roles, role)
	}
	return roles, nil
}

// Role is the resolver for the role field.
func (r *queryResolver) Role(ctx context.Context, name string) (*graph.Role, error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanAdmin(userCtx.SubjectPermissions, model.AdminSectionRoles, model.ActionRead) {
		return nil, fmt.Errorf("user %s has no permission to access %s", userCtx.Username, model.AdminSectionRoles)
	}
	dbRole, err := r.RoleService.GetByCode(ctx, name, model.RoleTypeRole)
	if err != nil {
		return nil, err
	}
	role := &graph.Role{Name: name, CreatedAt: dbRole.CreatedAt, UpdatedAt: dbRole.UpdatedAt}
	subjectPermissions, errGetPerms := r.RoleService.GetPermissionsByRoleCode(ctx, dbRole.Code)
	if errGetPerms != nil {
		return nil, errGetPerms
	}
	role.Resources = subjectPermissions.Resources
	role.Admin = subjectPermissions.Admin

	return role, nil
}

// SearchRoles is the resolver for the searchRoles field.
func (r *queryResolver) SearchRoles(ctx context.Context, pagination *types.PaginationInput, filter graph.RoleFilter, sort []database.SortInput) (*graph.RoleList, error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanAdmin(userCtx.SubjectPermissions, model.AdminSectionRoles, model.ActionRead) {
		return nil, fmt.Errorf("user %s has no permission to access %s", userCtx.Username, model.AdminSectionRoles)
	}
	query := r.DB.Model(&model.Role{}).Where("type = ?", model.RoleTypeRole)

	if filter.Search != nil && *filter.Search != "" {
		search := fmt.Sprintf("%%%s%%", *filter.Search)
		query = query.Where("code LIKE ?", search)
	}

	if len(sort) > 0 {
		query = database.ApplySort(query, model.RoleSortableColumns, sort, "")
	}

	roleList, err := r.RoleService.SearchPaginate(ctx, pagination, query)
	if err != nil {
		return nil, err
	}
	roles := &graph.RoleList{
		Total:  roleList.Total,
		Limit:  roleList.Limit,
		Offset: roleList.Offset,
	}
	for _, dbRole := range roleList.Items {
		role := graph.Role{
			Name:      dbRole.Code,
			CreatedAt: dbRole.CreatedAt,
			UpdatedAt: dbRole.UpdatedAt,
		}

		subjectPermissions, errGetPerms := r.RoleService.GetPermissionsByRoleCode(ctx, dbRole.Code)
		if errGetPerms != nil {
			return nil, errGetPerms
		}
		role.Resources = subjectPermissions.Resources
		role.Admin = subjectPermissions.Admin

		roles.Items = append(roles.Items, role)
	}

	return roles, nil
}

// Type is the resolver for the type field.
func (r *resourcePermissionResolver) Type(ctx context.Context, obj *model.ResourcePermission) (string, error) {
	return string(obj.Role.Type), nil
}

// Action is the resolver for the action field.
func (r *resourcePermissionResolver) Action(ctx context.Context, obj *model.ResourcePermission) (string, error) {
	return string(obj.Action), nil
}

// AdminPermission returns graph.AdminPermissionResolver implementation.
func (r *Resolver) AdminPermission() graph.AdminPermissionResolver {
	return &adminPermissionResolver{r}
}

// ResourcePermission returns graph.ResourcePermissionResolver implementation.
func (r *Resolver) ResourcePermission() graph.ResourcePermissionResolver {
	return &resourcePermissionResolver{r}
}

type adminPermissionResolver struct{ *Resolver }
type resourcePermissionResolver struct{ *Resolver }
