package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/flectolab/flecto-manager/auth"
	commonTypes "github.com/flectolab/flecto-manager/common/types"
	"github.com/flectolab/flecto-manager/database"
	"github.com/flectolab/flecto-manager/graph"
	"github.com/flectolab/flecto-manager/hash"
	"github.com/flectolab/flecto-manager/model"
	"github.com/flectolab/flecto-manager/types"
)

// Active is the resolver for the active field.
func (r *meResolver) Active(ctx context.Context, obj *model.User) (bool, error) {
	return obj.IsActive(), nil
}

// Permissions is the resolver for the permissions field.
func (r *meResolver) Permissions(ctx context.Context, obj *model.User) (*model.SubjectPermissions, error) {
	userCtx := auth.GetUser(ctx)
	subjectPermissions, err := r.RoleService.GetPermissionsByUsername(ctx, obj.Username)
	if err != nil {
		return nil, err
	}
	subjectPermissions.Append(userCtx.SubjectPermissions)
	return subjectPermissions, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input graph.CreateUserInput) (*model.User, error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanAdmin(userCtx.SubjectPermissions, model.AdminSectionUsers, model.ActionWrite) {
		return nil, fmt.Errorf("user %s has no permission to access %s", userCtx.Username, model.AdminSectionUsers)
	}
	hashedPassword, err := hash.Password(input.Password)
	if err != nil {
		return nil, err
	}

	newUser := &model.User{
		Username:  input.Username,
		Password:  string(hashedPassword),
		Firstname: input.Firstname,
		Lastname:  input.Lastname,
		Active:    types.Ptr(true),
	}

	return r.UserService.Create(ctx, newUser)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id int64, input graph.UpdateUserInput) (*model.User, error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanAdmin(userCtx.SubjectPermissions, model.AdminSectionUsers, model.ActionWrite) {
		return nil, fmt.Errorf("user %s has no permission to access %s", userCtx.Username, model.AdminSectionUsers)
	}

	return r.UserService.Update(ctx, id, model.User{Firstname: input.Firstname, Lastname: input.Lastname})
}

// UpdateUserPermissions is the resolver for the updateUserPermissions field.
func (r *mutationResolver) UpdateUserPermissions(ctx context.Context, id int64, input graph.SubjectPermissionsInput) (*model.User, error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanAdmin(userCtx.SubjectPermissions, model.AdminSectionUsers, model.ActionWrite) {
		return nil, fmt.Errorf("user %s has no permission to access %s", userCtx.Username, model.AdminSectionUsers)
	}

	// Fetch user to return
	user, errFetchUser := r.UserService.GetByID(ctx, id)
	if errFetchUser != nil {
		return nil, errFetchUser
	}
	role, errFetchRole := r.RoleService.GetByCode(ctx, user.Username, model.RoleTypeUser)
	if errFetchRole != nil {
		return nil, errFetchRole
	}
	subjectPermissions := &model.SubjectPermissions{}
	// Convert input to auth types
	for _, resource := range input.Resources {
		subjectPermissions.Resources = append(subjectPermissions.Resources, model.ResourcePermission{
			Namespace: resource.Namespace,
			Project:   resource.Project,
			Resource:  model.ResourceType(resource.Resource),
			Action:    model.ActionType(resource.Action),
		})
	}

	for _, a := range input.Admin {
		subjectPermissions.Admin = append(subjectPermissions.Admin, model.AdminPermission{
			Section: model.SectionType(a.Section),
			Action:  model.ActionType(a.Action),
		})
	}

	err := r.RoleService.UpdateRolePermissions(ctx, role.ID, subjectPermissions)
	if err != nil {
		return nil, err
	}

	err = r.RoleService.UpdateUserRoles(ctx, user.ID, input.Roles)
	if err != nil {
		return nil, err
	}

	return user, nil
}

// UpdateUserStatus is the resolver for the updateUserStatus field.
func (r *mutationResolver) UpdateUserStatus(ctx context.Context, id int64, input graph.UpdateUserStatusInput) (*model.User, error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanAdmin(userCtx.SubjectPermissions, model.AdminSectionUsers, model.ActionWrite) {
		return nil, fmt.Errorf("user %s has no permission to access %s", userCtx.Username, model.AdminSectionUsers)
	}

	return r.UserService.UpdateStatus(ctx, id, *input.Active)
}

// UpdateUserPassword is the resolver for the updateUserPassword field.
func (r *mutationResolver) UpdateUserPassword(ctx context.Context, id int64, input graph.UpdateUserPasswordInput) (*model.User, error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanAdmin(userCtx.SubjectPermissions, model.AdminSectionUsers, model.ActionWrite) {
		return nil, fmt.Errorf("user %s has no permission to access %s", userCtx.Username, model.AdminSectionUsers)
	}

	err := r.UserService.UpdatePassword(ctx, id, input.NewPassword)
	if err != nil {
		return nil, err
	}

	return r.UserService.GetByID(ctx, id)
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id int64) (bool, error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanAdmin(userCtx.SubjectPermissions, model.AdminSectionUsers, model.ActionWrite) {
		return false, fmt.Errorf("user %s has no permission to access %s", userCtx.Username, model.AdminSectionUsers)
	}

	return r.UserService.Delete(ctx, id)
}

// MeUpdatePassword is the resolver for the meUpdatePassword field.
func (r *mutationResolver) MeUpdatePassword(ctx context.Context, input graph.MeUpdatePasswordInput) (*model.User, error) {
	userCtx := auth.GetUser(ctx)
	if userCtx.AuthType != types.AuthTypeBasic {
		return nil, fmt.Errorf("user must authenticated with basic auth")
	}

	if len(input.NewPassword) < 8 {
		return nil, fmt.Errorf("new password must be at least 8 characters")
	}

	// Fetch the user to verify old password
	user, err := r.UserService.GetByID(ctx, userCtx.UserID)
	if err != nil {
		return nil, err
	}

	// Verify old password
	if err = hash.CheckPassword(user.Password, input.OldPassword); err != nil {
		return nil, fmt.Errorf("current password is incorrect")
	}

	err = r.UserService.UpdatePassword(ctx, userCtx.UserID, input.NewPassword)
	if err != nil {
		return nil, err
	}

	return user, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userCtx := auth.GetUser(ctx)
	return r.UserService.GetByID(ctx, userCtx.UserID)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, pagination *commonTypes.PaginationInput) (*commonTypes.PaginatedResult[model.User], error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanAdmin(userCtx.SubjectPermissions, model.AdminSectionUsers, model.ActionRead) {
		return nil, fmt.Errorf("user %s has no permission to access %s", userCtx.Username, model.AdminSectionUsers)
	}

	return r.UserService.SearchPaginate(ctx, pagination, nil)
}

// SearchUsers is the resolver for the searchUsers field.
func (r *queryResolver) SearchUsers(ctx context.Context, pagination *commonTypes.PaginationInput, filter graph.UserFilter, sort []database.SortInput) (*commonTypes.PaginatedResult[model.User], error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanAdmin(userCtx.SubjectPermissions, model.AdminSectionUsers, model.ActionRead) {
		return nil, fmt.Errorf("user %s has no permission to access %s", userCtx.Username, model.AdminSectionUsers)
	}

	query := r.UserService.GetQuery(ctx)

	if filter.Active != nil {
		query = query.Where("active = ?", *filter.Active)
	}

	if filter.Search != nil && *filter.Search != "" {
		search := fmt.Sprintf("%%%s%%", *filter.Search)
		query = query.Where("username LIKE ? OR lastname LIKE ? OR firstname LIKE ?", search, search, search)
	}

	if len(sort) > 0 {
		query = database.ApplySort(query, model.UserSortableColumns, sort, "")
	}

	return r.UserService.SearchPaginate(ctx, pagination, query)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, username string) (*model.User, error) {
	userCtx := auth.GetUser(ctx)
	if !r.PermissionChecker.CanAdmin(userCtx.SubjectPermissions, model.AdminSectionUsers, model.ActionRead) {
		return nil, fmt.Errorf("user %s has no permission to access %s", userCtx.Username, model.AdminSectionUsers)
	}
	return r.UserService.GetByUsername(ctx, username)
}

// Active is the resolver for the active field.
func (r *userResolver) Active(ctx context.Context, obj *model.User) (bool, error) {
	return obj.IsActive(), nil
}

// Roles is the resolver for the roles field.
func (r *userResolver) Roles(ctx context.Context, obj *model.User) ([]model.Role, error) {
	// Get all roles for this user (personal role type="user" + assigned roles type="role")
	return r.RoleService.GetUserRoles(ctx, obj.ID)
}

// Me returns graph.MeResolver implementation.
func (r *Resolver) Me() graph.MeResolver { return &meResolver{r} }

// User returns graph.UserResolver implementation.
func (r *Resolver) User() graph.UserResolver { return &userResolver{r} }

type meResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
